name: Deploy to AWS
on:
  push:
    branch: [ deploy-to-ecs]
  jobs:
    build-and-deploy:
      runs-on: [ centos-latest ]
      steps:
        - name: Checkout source
          uses: actions/checkout@v3
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            java-version: '19'
        - name: Build Project
          run: mvn clean install -DskipTests